# Generated by Django 3.2 on 2021-04-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0006_auto_20210406_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='zone',
        ),
        migrations.AddField(
            model_name='zone',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zones.agency'),
        ),
    ]
