# Generated by Django 3.2 on 2021-04-06 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0007_auto_20210406_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='agency',
        ),
        migrations.AddField(
            model_name='agency',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zones.zone'),
        ),
    ]
