# Generated by Django 3.2 on 2021-04-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0008_auto_20210406_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='zones.zone'),
        ),
    ]
