# Generated by Django 3.2 on 2021-04-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0011_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ext',
            field=models.CharField(help_text='eg.: 5068, 4563754, 4685051', max_length=25, verbose_name='extension'),
        ),
    ]
