# Generated by Django 3.2 on 2021-04-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0013_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
